name: airbyte_utils
version: '1.0'
config-version: 2
profile: BRC
model-paths:
- models
docs-paths:
- docs
analysis-paths:
- analysis
test-paths:
- tests
seed-paths:
- data
macro-paths:
- macros
target-path: ../build
log-path: ../logs
packages-install-path: ../dbt
clean-targets:
- build
- dbt_modules
quoting:
  database: true
  schema: false
  identifier: true
models:
  +transient: false
  airbyte_utils:
    +materialized: table
    generated:
      airbyte_ctes:
        +tags: airbyte_internal_cte
        +materialized: ephemeral
      airbyte_incremental:
        +tags: incremental_tables
        +materialized: incremental
        +on_schema_change: sync_all_columns
      airbyte_tables:
        +tags: normalized_tables
        +materialized: table
      airbyte_views:
        +tags: airbyte_internal_views
        +materialized: view
dispatch:
- macro_namespace: dbt_utils
  search_order:
  - airbyte_utils
  - dbt_utils
vars:
  json_column: _airbyte_data
  models_to_source:
    CAMPAIGNS_AB1: BRC._AIRBYTE_RAW_CAMPAIGNS
    CAMPAIGNS_AB2: BRC._AIRBYTE_RAW_CAMPAIGNS
    CAMPAIGNS: BRC._AIRBYTE_RAW_CAMPAIGNS
    ADMIN_LOGINS_AB1: BRC._AIRBYTE_RAW_ADMIN_LOGINS
    ADMIN_LOGINS_AB2: BRC._AIRBYTE_RAW_ADMIN_LOGINS
    ADMIN_LOGINS: BRC._AIRBYTE_RAW_ADMIN_LOGINS
    ADMINS_AB1: BRC._AIRBYTE_RAW_ADMINS
    ADMINS_AB2: BRC._AIRBYTE_RAW_ADMINS
    ADMINS: BRC._AIRBYTE_RAW_ADMINS
    ADVERTISER_PAYERS_AB1: BRC._AIRBYTE_RAW_ADVERTISER_PAYERS
    ADVERTISER_PAYERS_AB2: BRC._AIRBYTE_RAW_ADVERTISER_PAYERS
    ADVERTISER_PAYERS: BRC._AIRBYTE_RAW_ADVERTISER_PAYERS
    ADVERTISER_PAYMENTS_AB1: BRC._AIRBYTE_RAW_ADVERTISER_PAYMENTS
    ADVERTISER_PAYMENTS_AB2: BRC._AIRBYTE_RAW_ADVERTISER_PAYMENTS
    ADVERTISER_PAYMENTS: BRC._AIRBYTE_RAW_ADVERTISER_PAYMENTS
    ADVERTISER_PAYMENTS_DETAILS_AB1: BRC._AIRBYTE_RAW_ADVERTISER_PAYMENTS_DETAILS
    ADVERTISER_PAYMENTS_DETAILS_AB2: BRC._AIRBYTE_RAW_ADVERTISER_PAYMENTS_DETAILS
    ADVERTISER_PAYMENTS_DETAILS: BRC._AIRBYTE_RAW_ADVERTISER_PAYMENTS_DETAILS
    ADVERTISER_PAYMENTS_DETAILS_PAID_AB1: BRC._AIRBYTE_RAW_ADVERTISER_PAYMENTS_DETAILS_PAID
    ADVERTISER_PAYMENTS_DETAILS_PAID_AB2: BRC._AIRBYTE_RAW_ADVERTISER_PAYMENTS_DETAILS_PAID
    ADVERTISER_PAYMENTS_DETAILS_PAID: BRC._AIRBYTE_RAW_ADVERTISER_PAYMENTS_DETAILS_PAID
    ADVERTISERS_AB1: BRC._AIRBYTE_RAW_ADVERTISERS
    ADVERTISERS_AB2: BRC._AIRBYTE_RAW_ADVERTISERS
    ADVERTISERS: BRC._AIRBYTE_RAW_ADVERTISERS
    AFFILIATE_SYSTEMS_AB1: BRC._AIRBYTE_RAW_AFFILIATE_SYSTEMS
    AFFILIATE_SYSTEMS_AB2: BRC._AIRBYTE_RAW_AFFILIATE_SYSTEMS
    AFFILIATE_SYSTEMS: BRC._AIRBYTE_RAW_AFFILIATE_SYSTEMS
    API_ACCESS_AB1: BRC._AIRBYTE_RAW_API_ACCESS
    API_ACCESS_AB2: BRC._AIRBYTE_RAW_API_ACCESS
    API_ACCESS: BRC._AIRBYTE_RAW_API_ACCESS
    BRANDS_AB1: BRC._AIRBYTE_RAW_BRANDS
    BRANDS_AB2: BRC._AIRBYTE_RAW_BRANDS
    BRANDS: BRC._AIRBYTE_RAW_BRANDS
    CAMPAIGN_DEAL_REQUESTS_AB1: BRC._AIRBYTE_RAW_CAMPAIGN_DEAL_REQUESTS
    CAMPAIGN_DEAL_REQUESTS_AB2: BRC._AIRBYTE_RAW_CAMPAIGN_DEAL_REQUESTS
    CAMPAIGN_DEAL_REQUESTS: BRC._AIRBYTE_RAW_CAMPAIGN_DEAL_REQUESTS
    CAMPAIGN_DEALS_AB1: BRC._AIRBYTE_RAW_CAMPAIGN_DEALS
    CAMPAIGN_DEALS_AB2: BRC._AIRBYTE_RAW_CAMPAIGN_DEALS
    CAMPAIGN_DEALS: BRC._AIRBYTE_RAW_CAMPAIGN_DEALS
    CAMPAIGN_MATERIALS_AB1: BRC._AIRBYTE_RAW_CAMPAIGN_MATERIALS
    CAMPAIGN_MATERIALS_AB2: BRC._AIRBYTE_RAW_CAMPAIGN_MATERIALS
    CAMPAIGN_MATERIALS: BRC._AIRBYTE_RAW_CAMPAIGN_MATERIALS
    CAMPAIGN_MATERIALS_REQUEST_NEW_AB1: BRC._AIRBYTE_RAW_CAMPAIGN_MATERIALS_REQUEST_NEW
    CAMPAIGN_MATERIALS_REQUEST_NEW_AB2: BRC._AIRBYTE_RAW_CAMPAIGN_MATERIALS_REQUEST_NEW
    CAMPAIGN_MATERIALS_REQUEST_NEW: BRC._AIRBYTE_RAW_CAMPAIGN_MATERIALS_REQUEST_NEW
    PAYMENT_DETAILS_AB1: BRC._AIRBYTE_RAW_PAYMENT_DETAILS
    PAYMENT_DETAILS_AB2: BRC._AIRBYTE_RAW_PAYMENT_DETAILS
    PAYMENT_DETAILS: BRC._AIRBYTE_RAW_PAYMENT_DETAILS
    PAYMENT_HISTORY_AB1: BRC._AIRBYTE_RAW_PAYMENT_HISTORY
    PAYMENT_HISTORY_AB2: BRC._AIRBYTE_RAW_PAYMENT_HISTORY
    PAYMENT_HISTORY: BRC._AIRBYTE_RAW_PAYMENT_HISTORY
    PAYMENTS_AB1: BRC._AIRBYTE_RAW_PAYMENTS
    PAYMENTS_AB2: BRC._AIRBYTE_RAW_PAYMENTS
    PAYMENTS: BRC._AIRBYTE_RAW_PAYMENTS
    POSTBACK_3RD_PARTY_LOG_AB1: BRC._AIRBYTE_RAW_POSTBACK_3RD_PARTY_LOG
    POSTBACK_3RD_PARTY_LOG_AB2: BRC._AIRBYTE_RAW_POSTBACK_3RD_PARTY_LOG
    POSTBACK_3RD_PARTY_LOG: BRC._AIRBYTE_RAW_POSTBACK_3RD_PARTY_LOG
    POSTBACK_3RD_PARTY_URLS_AB1: BRC._AIRBYTE_RAW_POSTBACK_3RD_PARTY_URLS
    POSTBACK_3RD_PARTY_URLS_AB2: BRC._AIRBYTE_RAW_POSTBACK_3RD_PARTY_URLS
    POSTBACK_3RD_PARTY_URLS: BRC._AIRBYTE_RAW_POSTBACK_3RD_PARTY_URLS
    POSTBACK_ADVERTISER_DOMAIN_AB1: BRC._AIRBYTE_RAW_POSTBACK_ADVERTISER_DOMAIN
    POSTBACK_ADVERTISER_DOMAIN_AB2: BRC._AIRBYTE_RAW_POSTBACK_ADVERTISER_DOMAIN
    POSTBACK_ADVERTISER_DOMAIN: BRC._AIRBYTE_RAW_POSTBACK_ADVERTISER_DOMAIN
    POSTBACK_DOMAINS_AB1: BRC._AIRBYTE_RAW_POSTBACK_DOMAINS
    POSTBACK_DOMAINS_AB2: BRC._AIRBYTE_RAW_POSTBACK_DOMAINS
    POSTBACK_DOMAINS: BRC._AIRBYTE_RAW_POSTBACK_DOMAINS
    POSTBACK_TRACKING_VALUES_AB1: BRC._AIRBYTE_RAW_POSTBACK_TRACKING_VALUES
    POSTBACK_TRACKING_VALUES_AB2: BRC._AIRBYTE_RAW_POSTBACK_TRACKING_VALUES
    POSTBACK_TRACKING_VALUES: BRC._AIRBYTE_RAW_POSTBACK_TRACKING_VALUES
    PROMOTIONS_AB1: BRC._AIRBYTE_RAW_PROMOTIONS
    PROMOTIONS_AB2: BRC._AIRBYTE_RAW_PROMOTIONS
    PROMOTIONS: BRC._AIRBYTE_RAW_PROMOTIONS
    PUBLISHER_LOGINS_AB1: BRC._AIRBYTE_RAW_PUBLISHER_LOGINS
    PUBLISHER_LOGINS_AB2: BRC._AIRBYTE_RAW_PUBLISHER_LOGINS
    PUBLISHER_LOGINS: BRC._AIRBYTE_RAW_PUBLISHER_LOGINS
    PUBLISHER_MANAGERS_AB1: BRC._AIRBYTE_RAW_PUBLISHER_MANAGERS
    PUBLISHER_MANAGERS_AB2: BRC._AIRBYTE_RAW_PUBLISHER_MANAGERS
    PUBLISHER_MANAGERS: BRC._AIRBYTE_RAW_PUBLISHER_MANAGERS
    PUBLISHER_NEWS_AB1: BRC._AIRBYTE_RAW_PUBLISHER_NEWS
    PUBLISHER_NEWS_AB2: BRC._AIRBYTE_RAW_PUBLISHER_NEWS
    PUBLISHER_NEWS: BRC._AIRBYTE_RAW_PUBLISHER_NEWS
    PUBLISHER_NEWS_SEEN_AB1: BRC._AIRBYTE_RAW_PUBLISHER_NEWS_SEEN
    PUBLISHER_NEWS_SEEN_AB2: BRC._AIRBYTE_RAW_PUBLISHER_NEWS_SEEN
    PUBLISHER_NEWS_SEEN: BRC._AIRBYTE_RAW_PUBLISHER_NEWS_SEEN
    PUBLISHERS_AB1: BRC._AIRBYTE_RAW_PUBLISHERS
    PUBLISHERS_AB2: BRC._AIRBYTE_RAW_PUBLISHERS
    PUBLISHERS: BRC._AIRBYTE_RAW_PUBLISHERS
    STATS_ERRORS_AB1: BRC._AIRBYTE_RAW_STATS_ERRORS
    STATS_ERRORS_AB2: BRC._AIRBYTE_RAW_STATS_ERRORS
    STATS_ERRORS: BRC._AIRBYTE_RAW_STATS_ERRORS
    SUB_PUBLISHERS_AB1: BRC._AIRBYTE_RAW_SUB_PUBLISHERS
    SUB_PUBLISHERS_AB2: BRC._AIRBYTE_RAW_SUB_PUBLISHERS
    SUB_PUBLISHERS: BRC._AIRBYTE_RAW_SUB_PUBLISHERS
    POSTBACK_TRACKING_AB1: BRC._AIRBYTE_RAW_POSTBACK_TRACKING
    POSTBACK_TRACKING_AB2: BRC._AIRBYTE_RAW_POSTBACK_TRACKING
    POSTBACK_TRACKING_STG: BRC._AIRBYTE_RAW_POSTBACK_TRACKING
    POSTBACK_TRACKING_SCD: BRC._AIRBYTE_RAW_POSTBACK_TRACKING
    POSTBACK_TRACKING: BRC._AIRBYTE_RAW_POSTBACK_TRACKING
    POSTBACK_3RD_PARTY_CLICK_LOG_AB1: BRC._AIRBYTE_RAW_POSTBACK_3RD_PARTY_CLICK_LOG
    POSTBACK_3RD_PARTY_CLICK_LOG_AB2: BRC._AIRBYTE_RAW_POSTBACK_3RD_PARTY_CLICK_LOG
    POSTBACK_3RD_PARTY_CLICK_LOG_STG: BRC._AIRBYTE_RAW_POSTBACK_3RD_PARTY_CLICK_LOG
    POSTBACK_3RD_PARTY_CLICK_LOG_SCD: BRC._AIRBYTE_RAW_POSTBACK_3RD_PARTY_CLICK_LOG
    POSTBACK_3RD_PARTY_CLICK_LOG: BRC._AIRBYTE_RAW_POSTBACK_3RD_PARTY_CLICK_LOG