{{ 
    config(
        materialized='view',
        database=env_var('STG_DATABASE'),
        schema="SPREE"
    ) 
}}

WITH VOL_REDTK_CONVERSION AS (
    SELECT DISTINCT
        CLICKID,
        CAMPAIGN_NAME,
        BROWSER,
        BROWSER_VERSION,
        DEVICE_NAME,
        '' AS DEVICE_BRAND,
        OS AS OPERATOR_SYSTEM,
        OS_VERSION,
        'Voluum' AS SOURCE_SYSTEM,
        _AIRBYTE_EMITTED_AT
    FROM {{ source('VOLUUM', 'CONVERSIONS') }}
    WHERE CONVERSION_TYPE IN ('signup', 'signup', 'first_deposit')
    UNION ALL
    SELECT DISTINCT
        CLICKID,
        CAMPAIGN AS CAMPAIGN_NAME,
        BROWSER,
        '' AS BROWSER_VERSION,
        DEVICE AS DEVICE_NAME,
        DEVICE_BRAND,
        OS AS OPERATOR_SYSTEM,
        '' AS OS_VERSION,
        'RedTrack' AS SOURCE_SYSTEM,
        MAX(_AIRBYTE_EMITTED_AT) AS _AIRBYTE_EMITTED_AT
    FROM {{ source('REDTRACK', 'CONVERSIONS') }}
    GROUP BY 1, 2, 3, 4, 5, 6, 7, 8, 9
),

FINAL_JOIN AS (
    SELECT
        REG.DATE,
        REG.AFP,
        CMP.SOURCE_SYSTEM AS CAMP_SOURCE_SYTEM,
        REG.COMMISSION,
        REG.COMMISSIONS,
        REG.DEPOSITS,
        REG.DEPOSIT_COUNT,
        REG.EXTERNAL_DATE,
        REG.FIRST_DEPOSIT,
        REG.FIRST_DEPOSIT_DATE,
        REG.NET_DEPOSITS,
        REG.QUALIFICATION_DATE,
        REG.WITHDRAWALS,
        REG.PL,
        REG.GENERIC_1,
        REG.GENERIC_2,
        REG.COUNTRY,
        REG.REGISTRATION_DATE,
        REG.STATUS,
        PSTBK.POST_KEYWORD,
        CMP.BROWSER,
        CMP.BROWSER_VERSION,
        CMP.DEVICE_NAME,
        CMP.DEVICE_BRAND,
        CMP.OPERATOR_SYSTEM,
        CMP.OS_VERSION,
        REG.USERID,
        REG.TRACKING_CODE,
        REG.TRACKER_LOGIN_ID,
        COALESCE(CMP.CAMPAIGN_NAME, 'Unknown') AS CAMPAIGN_NAME,
        REG._AIRBYTE_EMITTED_AT,
        REG._AIRBYTE_NORMALIZED_AT
    FROM {{ source('SWEEP', 'ICT_FTD_REGISTRATION_REPORT') }} AS REG
    LEFT OUTER JOIN {{ source('BRC', 'POSTBACK_TRACKING') }} AS PSTBK
        ON UPPER(REG.AFP) = UPPER(PSTBK.POST_CLICKID)
    LEFT OUTER JOIN VOL_REDTK_CONVERSION AS CMP
        ON UPPER(PSTBK.POST_3RD_PARTY_CLICKID) = UPPER(CMP.CLICKID)
)

SELECT
    DATE,
    AFP,
    CAMPAIGN_NAME,
    CAMP_SOURCE_SYTEM,
    COMMISSION,
    COMMISSIONS,
    DEPOSITS,
    DEPOSIT_COUNT,
    EXTERNAL_DATE,
    FIRST_DEPOSIT,
    FIRST_DEPOSIT_DATE,
    NET_DEPOSITS,
    QUALIFICATION_DATE,
    WITHDRAWALS,
    PL,
    GENERIC_1,
    GENERIC_2,
    COUNTRY,
    REGISTRATION_DATE,
    STATUS,
    USERID,
    TRACKING_CODE,
    TRACKER_LOGIN_ID,
    CAST(POST_KEYWORD AS VARCHAR(200)) AS POST_KEYWORD,
    CAST(BROWSER AS VARCHAR(200)) AS BROWSER,
    CAST(BROWSER_VERSION AS VARCHAR(200)) AS BROWSER_VERSION,
    CAST(DEVICE_NAME AS VARCHAR(200)) AS DEVICE_NAME,
    CAST(DEVICE_BRAND AS VARCHAR(200)) AS DEVICE_BRAND,
    CAST(OPERATOR_SYSTEM AS VARCHAR(200)) AS OPERATOR_SYSTEM,
    CAST(OS_VERSION AS VARCHAR(200)) AS OS_VERSION,
    _AIRBYTE_EMITTED_AT,
    _AIRBYTE_NORMALIZED_AT
FROM FINAL_JOIN
