{{ 
    config(
        materialized='view',
        database=env_var('STG_DATABASE'),
        schema="SPREE"
    ) 
}}

WITH VOL_REDTK_CONVERSION AS (
    SELECT DISTINCT
        CLICKID,
        CAMPAIGN_NAME,
        BROWSER,
        BROWSER_VERSION,
        DEVICE_NAME,
        '' AS DEVICE_BRAND,
        OS AS OPERATOR_SYSTEM,
        OS_VERSION,
        'Voluum' AS SOURCE_SYSTEM,
        _AIRBYTE_EMITTED_AT
    FROM {{ source('VOLUUM', 'CONVERSIONS') }}
    WHERE CONVERSION_TYPE IN ('signup', 'signup', 'first_deposit')
    UNION ALL
    SELECT DISTINCT
        CLICKID,
        CAMPAIGN AS CAMPAIGN_NAME,
        BROWSER,
        '' AS BROWSER_VERSION,
        DEVICE AS DEVICE_NAME,
        DEVICE_BRAND,
        OS AS OPERATOR_SYSTEM,
        '' AS OS_VERSION,
        'RedTrack' AS SOURCE_SYSTEM,
        MAX(_AIRBYTE_EMITTED_AT) AS _AIRBYTE_EMITTED_AT
    FROM {{ source('REDTRACK', 'CONVERSIONS') }}
    GROUP BY
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9
),

FINAL_JOIN AS (
    SELECT
        DV.DATE,
        DV.DEPOSITS,
        DV.WITHDRAWALS,
        DV.AFP,
        CMP.SOURCE_SYSTEM AS CAMP_SOURCE_SYTEM,
        DV.NET_DEPOSITS,
        DV.USERID,
        DV.COMMISSIONS,
        DV.BRAND,
        DV.VOLUME,
        DV.DEPOSIT_COUNT,
        DV.COMMISSION_COUNT,
        DV.POSITION_COUNT,
        DV.TRACKING_CODE,
        PSTBK.POST_KEYWORD,
        CMP.BROWSER,
        CMP.BROWSER_VERSION,
        CMP.DEVICE_NAME,
        CMP.DEVICE_BRAND,
        CMP.OPERATOR_SYSTEM,
        CMP.OS_VERSION,
        DV.TRACKER_LOGIN_ID,
        DV.PL,
        COALESCE(CMP.CAMPAIGN_NAME, 'Unknown') AS CAMPAIGN_NAME,
        DV._AIRBYTE_EMITTED_AT,
        DV._AIRBYTE_NORMALIZED_AT
    FROM {{ source('SWEEP', 'DYNAMIC_VARIABLES_REPORT') }} AS DV
    LEFT OUTER JOIN {{ source('BRC', 'POSTBACK_TRACKING') }} AS PSTBK ON UPPER(DV.AFP) = UPPER(PSTBK.POST_CLICKID)
    LEFT OUTER JOIN VOL_REDTK_CONVERSION AS CMP ON UPPER(PSTBK.POST_3RD_PARTY_CLICKID) = UPPER(CMP.CLICKID)
)

SELECT
    DATE,
    DEPOSITS,
    WITHDRAWALS,
    AFP,
    CAMPAIGN_NAME,
    CAMP_SOURCE_SYTEM,
    NET_DEPOSITS,
    USERID,
    COMMISSIONS,
    BRAND,
    VOLUME,
    DEPOSIT_COUNT,
    COMMISSION_COUNT,
    POSITION_COUNT,
    TRACKING_CODE,
    TRACKER_LOGIN_ID,
    PL,
    CAST(POST_KEYWORD AS VARCHAR(200)) AS POST_KEYWORD,
    CAST(BROWSER AS VARCHAR(200)) AS BROWSER,
    CAST(BROWSER_VERSION AS VARCHAR(200)) AS BROWSER_VERSION,
    CAST(DEVICE_NAME AS VARCHAR(200)) AS DEVICE_NAME,
    CAST(DEVICE_BRAND AS VARCHAR(200)) AS DEVICE_BRAND,
    CAST(OPERATOR_SYSTEM AS VARCHAR(200)) AS OPERATOR_SYSTEM,
    CAST(OS_VERSION AS VARCHAR(200)) AS OS_VERSION,
    _AIRBYTE_EMITTED_AT,
    _AIRBYTE_NORMALIZED_AT
FROM FINAL_JOIN
