version: 2
sources:
- name: GOOGLE_ANALYTICS
  quoting:
    database: true
    schema: false
    identifier: false
  tables:
  - name: _AIRBYTE_RAW_DAILY_ACTIVE_USERS
    external:
      location: "@STG.GOOGLE_ANALYTICS.S3_ESTG_GA4_JSON_FF"
      pattern: "(?=.*/daily_active_users/)^.*"
      file_format: "STG.GOOGLE_ANALYTICS.JSON_FF"
      auto_refresh: false
      refresh_on_create: false
      partitions:
        - name: _AIRBYTE_EMMITTED_AT
          data_type: date
          expression: CAST(SPLIT_PART(SPLIT_PART(METADATA$FILENAME, '/', -1), '_', 2) AS DATE)
    columns:
      - name: _AIRBYTE_AB_ID
        data_type: VARCHAR(16777216)
        expression: "CAST(GET($1, '_airbyte_ab_id') AS VARCHAR(16777216))"
      - name: _AIRBYTE_DATA
        data_type: VARCHAR(16777216)
        expression: "GET($1, '_airbyte_data')"
      - name: _AIRBYTE_EMITTED_AT
        data_type: date
        expression: "CAST(SPLIT_PART(SPLIT_PART(METADATA$FILENAME, '/', -1), '_', 2) AS DATE)"
      - name: FILE_NAME
        data_type: VARCHAR(16777216)
        expression: "METADATA$FILENAME"
      - name: FILE_ROW_NUMBER
        data_type: NUMBER(38,0)
        expression: "METADATA$FILE_ROW_NUMBER"
      - name: PLATFORM_NAME
        data_type: VARCHAR(16777216)
        expression: "SPLIT_PART(METADATA$FILENAME, '/', 3)"
      - name: OPERATOR_NAME
        data_type: VARCHAR(16777216)
        expression: "SPLIT_PART(METADATA$FILENAME, '/', 4)"
      - name: ACCOUNT_NAME
        data_type: VARCHAR(16777216)
        expression: "SPLIT_PART(METADATA$FILENAME, '/', 5)"
      - name: S3_PATH
        data_type: VARCHAR(16777216)
        expression: "SPLIT_PART(METADATA$FILENAME, 'raw_data/', -1)"
  - name: _AIRBYTE_RAW_DEVICES
    external:
      location: "@STG.GOOGLE_ANALYTICS.S3_ESTG_GA4_JSON_FF"
      pattern: "(?=.*/devices/)^.*"
      file_format: "STG.CELLXPERT.JSON_FF"
      auto_refresh: false
      refresh_on_create: false
      partitions:
        - name: _AIRBYTE_EMMITTED_AT
          data_type: date
          expression: CAST(SPLIT_PART(SPLIT_PART(METADATA$FILENAME, '/', -1), '_', 2) AS DATE)
    columns:
      - name: _AIRBYTE_AB_ID
        data_type: VARCHAR(16777216)
        expression: "CAST(GET($1, '_airbyte_ab_id') AS VARCHAR(16777216))"
      - name: _AIRBYTE_DATA
        data_type: VARCHAR(16777216)
        expression: "GET($1, '_airbyte_data')"
      - name: _AIRBYTE_EMITTED_AT
        data_type: date
        expression: "CAST(SPLIT_PART(SPLIT_PART(METADATA$FILENAME, '/', -1), '_', 2) AS DATE)"
      - name: FILE_NAME
        data_type: VARCHAR(16777216)
        expression: "METADATA$FILENAME"
      - name: FILE_ROW_NUMBER
        data_type: NUMBER(38,0)
        expression: "METADATA$FILE_ROW_NUMBER"
      - name: PLATFORM_NAME
        data_type: VARCHAR(16777216)
        expression: "SPLIT_PART(METADATA$FILENAME, '/', 3)"
      - name: OPERATOR_NAME
        data_type: VARCHAR(16777216)
        expression: "SPLIT_PART(METADATA$FILENAME, '/', 4)"
      - name: ACCOUNT_NAME
        data_type: VARCHAR(16777216)
        expression: "SPLIT_PART(METADATA$FILENAME, '/', 5)"
      - name: S3_PATH
        data_type: VARCHAR(16777216)
        expression: "SPLIT_PART(METADATA$FILENAME, 'raw_data/', -1)"
  - name: _AIRBYTE_RAW_FOUR_WEEKLY_ACTIVE_USERS
    external:
      location: "@STG.GOOGLE_ANALYTICS.S3_ESTG_GA4_JSON_FF"
      pattern: "(?=.*/four_weekly_active_users/)^.*"
      file_format: "STG.CELLXPERT.JSON_FF"
      auto_refresh: false
      refresh_on_create: false
      partitions:
        - name: _AIRBYTE_EMMITTED_AT
          data_type: date
          expression: CAST(SPLIT_PART(SPLIT_PART(METADATA$FILENAME, '/', -1), '_', 2) AS DATE)
    columns:
      - name: _AIRBYTE_AB_ID
        data_type: VARCHAR(16777216)
        expression: "CAST(GET($1, '_airbyte_ab_id') AS VARCHAR(16777216))"
      - name: _AIRBYTE_DATA
        data_type: VARCHAR(16777216)
        expression: "GET($1, '_airbyte_data')"
      - name: _AIRBYTE_EMITTED_AT
        data_type: date
        expression: "CAST(SPLIT_PART(SPLIT_PART(METADATA$FILENAME, '/', -1), '_', 2) AS DATE)"
      - name: FILE_NAME
        data_type: VARCHAR(16777216)
        expression: "METADATA$FILENAME"
      - name: FILE_ROW_NUMBER
        data_type: NUMBER(38,0)
        expression: "METADATA$FILE_ROW_NUMBER"
      - name: PLATFORM_NAME
        data_type: VARCHAR(16777216)
        expression: "SPLIT_PART(METADATA$FILENAME, '/', 3)"
      - name: OPERATOR_NAME
        data_type: VARCHAR(16777216)
        expression: "SPLIT_PART(METADATA$FILENAME, '/', 4)"
      - name: ACCOUNT_NAME
        data_type: VARCHAR(16777216)
        expression: "SPLIT_PART(METADATA$FILENAME, '/', 5)"
      - name: S3_PATH
        data_type: VARCHAR(16777216)
        expression: "SPLIT_PART(METADATA$FILENAME, 'raw_data/', -1)"
  - name: _AIRBYTE_RAW_LOCATIONS
    external:
      location: "@STG.GOOGLE_ANALYTICS.S3_ESTG_GA4_JSON_FF"
      pattern: "(?=.*/locations/)^.*"
      file_format: "STG.CELLXPERT.JSON_FF"
      auto_refresh: false
      refresh_on_create: false
      partitions:
        - name: _AIRBYTE_EMMITTED_AT
          data_type: date
          expression: CAST(SPLIT_PART(SPLIT_PART(METADATA$FILENAME, '/', -1), '_', 2) AS DATE)
    columns:
      - name: _AIRBYTE_AB_ID
        data_type: VARCHAR(16777216)
        expression: "CAST(GET($1, '_airbyte_ab_id') AS VARCHAR(16777216))"
      - name: _AIRBYTE_DATA
        data_type: VARCHAR(16777216)
        expression: "GET($1, '_airbyte_data')"
      - name: _AIRBYTE_EMITTED_AT
        data_type: date
        expression: "CAST(SPLIT_PART(SPLIT_PART(METADATA$FILENAME, '/', -1), '_', 2) AS DATE)"
      - name: FILE_NAME
        data_type: VARCHAR(16777216)
        expression: "METADATA$FILENAME"
      - name: FILE_ROW_NUMBER
        data_type: NUMBER(38,0)
        expression: "METADATA$FILE_ROW_NUMBER"
      - name: PLATFORM_NAME
        data_type: VARCHAR(16777216)
        expression: "SPLIT_PART(METADATA$FILENAME, '/', 3)"
      - name: OPERATOR_NAME
        data_type: VARCHAR(16777216)
        expression: "SPLIT_PART(METADATA$FILENAME, '/', 4)"
      - name: ACCOUNT_NAME
        data_type: VARCHAR(16777216)
        expression: "SPLIT_PART(METADATA$FILENAME, '/', 5)"
      - name: S3_PATH
        data_type: VARCHAR(16777216)
        expression: "SPLIT_PART(METADATA$FILENAME, 'raw_data/', -1)"
  - name: _AIRBYTE_RAW_PAGES
    external:
      location: "@STG.GOOGLE_ANALYTICS.S3_ESTG_GA4_JSON_FF"
      pattern: "(?=.*/pages/)^.*)^.*"
      file_format: "STG.CELLXPERT.JSON_FF"
      auto_refresh: false
      refresh_on_create: false
      partitions:
        - name: _AIRBYTE_EMMITTED_AT
          data_type: date
          expression: CAST(SPLIT_PART(SPLIT_PART(METADATA$FILENAME, '/', -1), '_', 2) AS DATE)
    columns:
      - name: _AIRBYTE_AB_ID
        data_type: VARCHAR(16777216)
        expression: "CAST(GET($1, '_airbyte_ab_id') AS VARCHAR(16777216))"
      - name: _AIRBYTE_DATA
        data_type: VARCHAR(16777216)
        expression: "GET($1, '_airbyte_data')"
      - name: _AIRBYTE_EMITTED_AT
        data_type: date
        expression: "CAST(SPLIT_PART(SPLIT_PART(METADATA$FILENAME, '/', -1), '_', 2) AS DATE)"
      - name: FILE_NAME
        data_type: VARCHAR(16777216)
        expression: "METADATA$FILENAME"
      - name: FILE_ROW_NUMBER
        data_type: NUMBER(38,0)
        expression: "METADATA$FILE_ROW_NUMBER"
      - name: PLATFORM_NAME
        data_type: VARCHAR(16777216)
        expression: "SPLIT_PART(METADATA$FILENAME, '/', 3)"
      - name: OPERATOR_NAME
        data_type: VARCHAR(16777216)
        expression: "SPLIT_PART(METADATA$FILENAME, '/', 4)"
      - name: ACCOUNT_NAME
        data_type: VARCHAR(16777216)
        expression: "SPLIT_PART(METADATA$FILENAME, '/', 5)"
      - name: S3_PATH
        data_type: VARCHAR(16777216)
        expression: "SPLIT_PART(METADATA$FILENAME, 'raw_data/', -1)"
  - name: _AIRBYTE_RAW_TRAFFIC_SOURCES
    external:
      location: "@STG.GOOGLE_ANALYTICS.S3_ESTG_GA4_JSON_FF"
      pattern: "(?=.*/traffic_sources/)^.*)^.*"
      file_format: "STG.CELLXPERT.JSON_FF"
      auto_refresh: false
      refresh_on_create: false
      partitions:
        - name: _AIRBYTE_EMMITTED_AT
          data_type: date
          expression: CAST(SPLIT_PART(SPLIT_PART(METADATA$FILENAME, '/', -1), '_', 2) AS DATE)
    columns:
      - name: _AIRBYTE_AB_ID
        data_type: VARCHAR(16777216)
        expression: "CAST(GET($1, '_airbyte_ab_id') AS VARCHAR(16777216))"
      - name: _AIRBYTE_DATA
        data_type: VARCHAR(16777216)
        expression: "GET($1, '_airbyte_data')"
      - name: _AIRBYTE_EMITTED_AT
        data_type: date
        expression: "CAST(SPLIT_PART(SPLIT_PART(METADATA$FILENAME, '/', -1), '_', 2) AS DATE)"
      - name: FILE_NAME
        data_type: VARCHAR(16777216)
        expression: "METADATA$FILENAME"
      - name: FILE_ROW_NUMBER
        data_type: NUMBER(38,0)
        expression: "METADATA$FILE_ROW_NUMBER"
      - name: PLATFORM_NAME
        data_type: VARCHAR(16777216)
        expression: "SPLIT_PART(METADATA$FILENAME, '/', 3)"
      - name: OPERATOR_NAME
        data_type: VARCHAR(16777216)
        expression: "SPLIT_PART(METADATA$FILENAME, '/', 4)"
      - name: ACCOUNT_NAME
        data_type: VARCHAR(16777216)
        expression: "SPLIT_PART(METADATA$FILENAME, '/', 5)"
      - name: S3_PATH
        data_type: VARCHAR(16777216)
        expression: "SPLIT_PART(METADATA$FILENAME, 'raw_data/', -1)"
  - name: _AIRBYTE_RAW_WEBSITE_OVERVIEW
    external:
      location: "@STG.GOOGLE_ANALYTICS.S3_ESTG_GA4_JSON_FF"
      pattern: "(?=.*/website_overview/)^.*"
      file_format: "STG.CELLXPERT.JSON_FF"
      auto_refresh: false
      refresh_on_create: false
      partitions:
        - name: _AIRBYTE_EMMITTED_AT
          data_type: date
          expression: CAST(SPLIT_PART(SPLIT_PART(METADATA$FILENAME, '/', -1), '_', 2) AS DATE)
    columns:
      - name: _AIRBYTE_AB_ID
        data_type: VARCHAR(16777216)
        expression: "CAST(GET($1, '_airbyte_ab_id') AS VARCHAR(16777216))"
      - name: _AIRBYTE_DATA
        data_type: VARCHAR(16777216)
        expression: "GET($1, '_airbyte_data')"
      - name: _AIRBYTE_EMITTED_AT
        data_type: date
        expression: "CAST(SPLIT_PART(SPLIT_PART(METADATA$FILENAME, '/', -1), '_', 2) AS DATE)"
      - name: FILE_NAME
        data_type: VARCHAR(16777216)
        expression: "METADATA$FILENAME"
      - name: FILE_ROW_NUMBER
        data_type: NUMBER(38,0)
        expression: "METADATA$FILE_ROW_NUMBER"
      - name: PLATFORM_NAME
        data_type: VARCHAR(16777216)
        expression: "SPLIT_PART(METADATA$FILENAME, '/', 3)"
      - name: OPERATOR_NAME
        data_type: VARCHAR(16777216)
        expression: "SPLIT_PART(METADATA$FILENAME, '/', 4)"
      - name: ACCOUNT_NAME
        data_type: VARCHAR(16777216)
        expression: "SPLIT_PART(METADATA$FILENAME, '/', 5)"
      - name: S3_PATH
        data_type: VARCHAR(16777216)
        expression: "SPLIT_PART(METADATA$FILENAME, 'raw_data/', -1)"
  - name: _AIRBYTE_RAW_WEEKLY_ACTIVE_USERS
    external:
      location: "@STG.GOOGLE_ANALYTICS.S3_ESTG_GA4_JSON_FF"
      pattern: "(?=.*/weekly_active_users/)^.*"
      file_format: "STG.CELLXPERT.JSON_FF"
      auto_refresh: false
      refresh_on_create: false
      partitions:
        - name: _AIRBYTE_EMMITTED_AT
          data_type: date
          expression: CAST(SPLIT_PART(SPLIT_PART(METADATA$FILENAME, '/', -1), '_', 2) AS DATE)
    columns:
      - name: _AIRBYTE_AB_ID
        data_type: VARCHAR(16777216)
        expression: "CAST(GET($1, '_airbyte_ab_id') AS VARCHAR(16777216))"
      - name: _AIRBYTE_DATA
        data_type: VARCHAR(16777216)
        expression: "GET($1, '_airbyte_data')"
      - name: _AIRBYTE_EMITTED_AT
        data_type: date
        expression: "CAST(SPLIT_PART(SPLIT_PART(METADATA$FILENAME, '/', -1), '_', 2) AS DATE)"
      - name: FILE_NAME
        data_type: VARCHAR(16777216)
        expression: "METADATA$FILENAME"
      - name: FILE_ROW_NUMBER
        data_type: NUMBER(38,0)
        expression: "METADATA$FILE_ROW_NUMBER"
      - name: PLATFORM_NAME
        data_type: VARCHAR(16777216)
        expression: "SPLIT_PART(METADATA$FILENAME, '/', 3)"
      - name: OPERATOR_NAME
        data_type: VARCHAR(16777216)
        expression: "SPLIT_PART(METADATA$FILENAME, '/', 4)"
      - name: ACCOUNT_NAME
        data_type: VARCHAR(16777216)
        expression: "SPLIT_PART(METADATA$FILENAME, '/', 5)"
      - name: S3_PATH
        data_type: VARCHAR(16777216)
        expression: "SPLIT_PART(METADATA$FILENAME, 'raw_data/', -1)"
- name: PUBLIC
  database: "{{ env_var('snowflake_db_dbt') }}"
  tables:
    - name: S3_FILES_STATS
