{{ 
    config(
        materialized='view',
        database=env_var('STG_DATABASE'),
        schema="SPREE"
    ) 
}}
SELECT 
    DATE, 
    TRAFFIC_SOURCE, 
    AD_ACCOUNT_CUSTOMER_ID__GOOGLE_ADS AS ADS_ACCOUNT_CUSTOMER_ID, 
    CAMPAIGN, 
    CAMPAIGN_ID__GOOGLE_ADS AS CAMPAIGN_ID, 
    KEYWORD_ID__GOOGLE_ADS AS KEYWORD_ID, 
    KEYWORD__GOOGLE_ADS AS KEYWORD, 
    KEYWORD_MATCH_TYPE__GOOGLE_ADS AS KEYWORD_MATCH_TYPE,
    AD_GROUP_ID__GOOGLE_ADS AS AD_GROUP_ID,
    AD_GROUP_NAME__GOOGLE_ADS AS AD_GROUP_NAME,
    AD_GROUP_STATUS__GOOGLE_ADS AS AD_GROUP_STATUS,
    AD_GROUP_TYPE__GOOGLE_ADS AS AD_GROUP_TYPE,
    SUM(CAST(COST AS NUMERIC(38, 9))) AS COST,
    SUM(CLICKS) AS CLICKS, 
    SUM(IMPRESSIONS) AS IMPRESSIONS,
    SUM(INTERACTIONS__GOOGLE_ADS) AS INTERACTIONS,
    SUM(CONVERSIONS__GOOGLE_ADS) AS CONVERSIONS
FROM {{ source('ADS_DATA_FUNNEL', 'PROD_AWS_RAW_ALARICK_WS_SPREE_ADS_SPEND_KEYWORD') }}
GROUP BY 
    DATE,
	TRAFFIC_SOURCE,
	ADS_ACCOUNT_CUSTOMER_ID,
	CAMPAIGN,
	CAMPAIGN_ID,
	KEYWORD_ID,
	KEYWORD,
	KEYWORD_MATCH_TYPE,
	AD_GROUP_ID,
	AD_GROUP_NAME,
	AD_GROUP_STATUS,
	AD_GROUP_TYPE