{{ 
    config(
        materialized='view',
        database=env_var('STG_DATABASE'),
        schema="SPREE"
    ) 
}}
SELECT
	TLOG_ACCOUNT_ID,
	CAST(TLOG_CREATED AS TIMESTAMP_TZ) AS TLOG_CREATED,
	TLOG_CREATED_BY,
	TLOG_DELETED,
	TLOG_DONT_IMPORT,
	TLOG_ERROR,
	TLOG_FK_ADVERTISER,
	TLOG_FK_PUBLISHER,
	TLOG_HISTORY,
	TLOG_ID,
	CAST(TLOG_IMPORT_TIME AS DATETIME) AS TLOG_IMPORT_TIME,
	TLOG_NOTE,
	TLOG_PASSWORD,
	TLOG_REMOTE_KEY1,
	TLOG_REMOTE_KEY2,
	TLOG_REMOTE_KEY3,
	TLOG_STATUS,
	CAST(TLOG_STATUS_DATE AS DATETIME) AS TLOG_STATUS_DATE,
	TLOG_SUB,
	TLOG_TYPE,
	CAST(TLOG_UPDATED AS DATETIME) AS TLOG_UPDATED,
	TLOG_UPDATED_BY,
	TLOG_USERNAME,
	_AIRBYTE_AB_ID,
	_AIRBYTE_EMITTED_AT,
	_AIRBYTE_NORMALIZED_AT
FROM {{ source('BRC', 'TRACKER_LOGINS') }} AS a
