{{ 
    config(
        materialized='view',
        database=env_var('STG_DATABASE'),
        schema="SPREE"
    ) 
}}
SELECT 
      CAMP_CATEGORY
    , CAMP_COUNTRY
    , CAMP_CPA_IN
    , CAMP_CPA_OUT
    , CAMP_CPL_IN
    , CAMP_CPL_OUT
    , CAST(CAMP_CREATED AS TIMESTAMP_TZ) AS CAMP_CREATED
    , CAMP_CREATED_BY
    , CAMP_CURRENCY
    , CAMP_DEPOSIT_BASELINE
    , CAMP_DESCRIPTION
    , CAMP_DISPLAY_DEAL
    , CAST(CAMP_ENDED AS STRING) AS CAMP_ENDED
    , CAMP_FK_ADVERTISER
    , CAMP_FK_BRAND
    , CAMP_HIDDEN
    , CAMP_HISTORY
    , CAMP_HYBRID
    , CAMP_ID
    , CAMP_LANGUAGE
    , CAMP_LICENSED
    , CAMP_NAME
    , CAMP_REV_DEAL
    , CAMP_REV_IN
    , CAMP_REV_OUT
    , CAMP_STATUS
    , CAMP_TRAFFIC_SOURCE
    , CAMP_TYPE
    , CAST(CAMP_UPDATED AS DATETIME) AS CAMP_UPDATED
    , CAMP_UPDATED_BY
    , CAMP_WAGER_BASELINE
    , _AIRBYTE_AB_ID
    , _AIRBYTE_EMITTED_AT
    , _AIRBYTE_NORMALIZED_AT
FROM {{ source('BRC', 'CAMPAIGNS') }} AS a
