{{ 
    config(
        materialized='view',
        database=env_var('STG_DATABASE'),
        schema="SPREE"
    ) 
}}
SELECT
	CAMT_STATUS,
	CAMT_DISPLAY_DEAL,
	CAMT_SHOW,
	CAMT_CHILD_NAME,
	CAMT_CPL_OUT,
	CAMT_TYPE,
	CAMT_REV_OUT,
	CAMT_ID,
	CAMT_FK_ADVERTISER,
	CAMT_DEAL_DATE,
	CAMT_URL,
	CAMT_FK_LOGIN,
	CAMT_REV_IN,
	CAMT_FK_PUBLISHER,
	CAMT_CPL_IN,
	CAMT_CAMPAIGN_KEY,
	CAMT_CREATED_BY,
	CAMT_SUBID_ACTIVATED,
	CAMT_CHILD,
	CAMT_HIDDEN,
	CAMT_HISTORY,
	CAST(CAMT_CREATED AS DATETIME) AS CAMT_CREATED,
	CAMT_CPA_IN,
	CAMT_FK_CAMPAIGN,
	CAST(CAMT_PUBLISHER_LAST_VISIT AS DATETIME) AS CAMT_PUBLISHER_LAST_VISIT,
	CAST(CAMT_UPDATED AS DATETIME) AS CAMT_UPDATED,
	CAMT_UPDATED_BY,
	CAMT_CPA_OUT,
	_AIRBYTE_AB_ID,
	_AIRBYTE_EMITTED_AT,
	_AIRBYTE_NORMALIZED_AT
FROM {{ source('BRC', 'CAMPAIGN_TRACKERS') }} AS a
