name: airbyte_utils
version: '1.0'
config-version: 2
profile: ga4
model-paths:
- models
docs-paths:
- docs
analysis-paths:
- analysis
test-paths:
- tests
seed-paths:
- data
macro-paths:
- macros
target-path: ../build
log-path: ../logs
packages-install-path: ../dbt
clean-targets:
- build
- dbt_modules
quoting:
  database: true
  schema: false
  identifier: true
models:
  +transient: false
  airbyte_utils:
    +materialized: table
    generated:
      airbyte_ctes:
        +tags: airbyte_internal_cte
        +materialized: ephemeral
      airbyte_incremental:
        +tags: incremental_tables
        +materialized: incremental
        +on_schema_change: sync_all_columns
      airbyte_tables:
        +tags: normalized_tables
        +materialized: table
      airbyte_views:
        +tags: airbyte_internal_views
        +materialized: view
dispatch:
- macro_namespace: dbt_utils
  search_order:
  - airbyte_utils
  - dbt_utils
vars:
  json_column: _airbyte_data
  models_to_source:
    DAILY_ACTIVE_USERS_AB1: GOOGLE_ANALYTICS._AIRBYTE_RAW_DAILY_ACTIVE_USERS
    DAILY_ACTIVE_USERS_AB2: GOOGLE_ANALYTICS._AIRBYTE_RAW_DAILY_ACTIVE_USERS
    DAILY_ACTIVE_USERS_STG: GOOGLE_ANALYTICS._AIRBYTE_RAW_DAILY_ACTIVE_USERS
    DAILY_ACTIVE_USERS_SCD: GOOGLE_ANALYTICS._AIRBYTE_RAW_DAILY_ACTIVE_USERS
    DAILY_ACTIVE_USERS: GOOGLE_ANALYTICS._AIRBYTE_RAW_DAILY_ACTIVE_USERS
    DEVICES_AB1: GOOGLE_ANALYTICS._AIRBYTE_RAW_DEVICES
    DEVICES_AB2: GOOGLE_ANALYTICS._AIRBYTE_RAW_DEVICES
    DEVICES_STG: GOOGLE_ANALYTICS._AIRBYTE_RAW_DEVICES
    DEVICES_SCD: GOOGLE_ANALYTICS._AIRBYTE_RAW_DEVICES
    DEVICES: GOOGLE_ANALYTICS._AIRBYTE_RAW_DEVICES
    FOUR_WEEKLY_ACTIVE_USERS_AB1: GOOGLE_ANALYTICS._AIRBYTE_RAW_FOUR_WEEKLY_ACTIVE_USERS
    FOUR_WEEKLY_ACTIVE_USERS_AB2: GOOGLE_ANALYTICS._AIRBYTE_RAW_FOUR_WEEKLY_ACTIVE_USERS
    FOUR_WEEKLY_ACTIVE_USERS_STG: GOOGLE_ANALYTICS._AIRBYTE_RAW_FOUR_WEEKLY_ACTIVE_USERS
    FOUR_WEEKLY_ACTIVE_USERS_SCD: GOOGLE_ANALYTICS._AIRBYTE_RAW_FOUR_WEEKLY_ACTIVE_USERS
    FOUR_WEEKLY_ACTIVE_USERS: GOOGLE_ANALYTICS._AIRBYTE_RAW_FOUR_WEEKLY_ACTIVE_USERS
    LOCATIONS_AB1: GOOGLE_ANALYTICS._AIRBYTE_RAW_LOCATIONS
    LOCATIONS_AB2: GOOGLE_ANALYTICS._AIRBYTE_RAW_LOCATIONS
    LOCATIONS_STG: GOOGLE_ANALYTICS._AIRBYTE_RAW_LOCATIONS
    LOCATIONS_SCD: GOOGLE_ANALYTICS._AIRBYTE_RAW_LOCATIONS
    LOCATIONS: GOOGLE_ANALYTICS._AIRBYTE_RAW_LOCATIONS
    PAGES_AB1: GOOGLE_ANALYTICS._AIRBYTE_RAW_PAGES
    PAGES_AB2: GOOGLE_ANALYTICS._AIRBYTE_RAW_PAGES
    PAGES_STG: GOOGLE_ANALYTICS._AIRBYTE_RAW_PAGES
    PAGES_SCD: GOOGLE_ANALYTICS._AIRBYTE_RAW_PAGES
    PAGES: GOOGLE_ANALYTICS._AIRBYTE_RAW_PAGES
    TRAFFIC_SOURCES_AB1: GOOGLE_ANALYTICS._AIRBYTE_RAW_TRAFFIC_SOURCES
    TRAFFIC_SOURCES_AB2: GOOGLE_ANALYTICS._AIRBYTE_RAW_TRAFFIC_SOURCES
    TRAFFIC_SOURCES_STG: GOOGLE_ANALYTICS._AIRBYTE_RAW_TRAFFIC_SOURCES
    TRAFFIC_SOURCES_SCD: GOOGLE_ANALYTICS._AIRBYTE_RAW_TRAFFIC_SOURCES
    TRAFFIC_SOURCES: GOOGLE_ANALYTICS._AIRBYTE_RAW_TRAFFIC_SOURCES
    WEBSITE_OVERVIEW_AB1: GOOGLE_ANALYTICS._AIRBYTE_RAW_WEBSITE_OVERVIEW
    WEBSITE_OVERVIEW_AB2: GOOGLE_ANALYTICS._AIRBYTE_RAW_WEBSITE_OVERVIEW
    WEBSITE_OVERVIEW_STG: GOOGLE_ANALYTICS._AIRBYTE_RAW_WEBSITE_OVERVIEW
    WEBSITE_OVERVIEW_SCD: GOOGLE_ANALYTICS._AIRBYTE_RAW_WEBSITE_OVERVIEW
    WEBSITE_OVERVIEW: GOOGLE_ANALYTICS._AIRBYTE_RAW_WEBSITE_OVERVIEW
    WEEKLY_ACTIVE_USERS_AB1: GOOGLE_ANALYTICS._AIRBYTE_RAW_WEEKLY_ACTIVE_USERS
    WEEKLY_ACTIVE_USERS_AB2: GOOGLE_ANALYTICS._AIRBYTE_RAW_WEEKLY_ACTIVE_USERS
    WEEKLY_ACTIVE_USERS_STG: GOOGLE_ANALYTICS._AIRBYTE_RAW_WEEKLY_ACTIVE_USERS
    WEEKLY_ACTIVE_USERS_SCD: GOOGLE_ANALYTICS._AIRBYTE_RAW_WEEKLY_ACTIVE_USERS
    WEEKLY_ACTIVE_USERS: GOOGLE_ANALYTICS._AIRBYTE_RAW_WEEKLY_ACTIVE_USERS
    