{{ 
    config(
        materialized='table',
        database=env_var('RAW_DATABASE'),
        schema="FUNNEL_IO"
    ) 
}}
SELECT 
    DATE,
    CAMPAIGN_ID__MICROSOFT_ADVERTISING AS CAMPAIGN_ID,
    CAMPAIGN_NAME__MICROSOFT_ADVERTISING AS CAMPAIGN_NAME,
    KEYWORD__MICROSOFT_ADVERTISING AS KEYWORD,
    BID_MATCH_TYPE__MICROSOFT_ADVERTISING AS BID_MATCH_TYPE,
    DELIVERED_MATCH_TYPE__MICROSOFT_ADVERTISING AS DELIVERED_MATCH_TYPE,
    SUM(CLICKS__MICROSOFT_ADVERTISING) AS CLICKS,
    SUM(IMPRESSIONS__MICROSOFT_ADVERTISING) AS IMPRESSIONS, 
    SUM(CONVERSIONS__MICROSOFT_ADVERTISING) AS CONVERSIONS,
    SUM(COST) AS COST,
    CURRENT_TIMESTAMP() AS UPDATE_TIME
FROM {{ source('ADS_DATA_FUNNEL_STANDARD', 'PROD_AWS_RAW_STANDARD_WS_BING_KEYWORD_REPORT') }}
GROUP BY ALL