{{ 
    config(
        materialized='table',
        database=env_var('RAW_DATABASE'),
        schema="FUNNEL_IO"
    ) 
}}
SELECT 
    DATE, 
    AD_GROUP_ID,
    AD_GROUP_NAME,
    CAMPAIGN,
    CAMPAIGN_ID, 
    KEYWORD, 
    SEARCH_TERM,
    AD_ACCOUNT_CUSTOMER_ID, 
    TRAFFIC_SOURCE, 
    SUM(CAST(COST AS NUMERIC(38, 9))) AS COST,
    SUM(CLICKS) AS CLICKS, 
    SUM(IMPRESSIONS) AS IMPRESSIONS,
    SUM(INTERACTIONS) AS INTERACTIONS,
    SUM(CONVERSIONS) AS CONVERSIONS,
    CURRENT_TIMESTAMP() AS UPDATE_TIME 
FROM {{ source('ADS_DATA_FUNNEL_STANDARD', 'PROD_AWS_RAW_STANDARD_WS_GOOGLE_ADS_GOOGLE_SEARCH_QUERY') }}
GROUP BY ALL