FROM ${AIRFLOW_IMAGE_NAME:-apache/airflow:2.5.1}
USER airflow
COPY requirements.txt /requirements.txt
RUN pip install --no-cache-dir --user -r /requirements.txt
RUN pip install apache-airflow-providers-airbyte[http] \
&& pip install apache-airflow-providers-airbyte \
&& pip install apache-airflow-providers-snowflake 